In [ ]:
# 乱数のシードを設定して再現性を確保
import numpy as np
import pandas as pd

np.random.seed(42)

# データ生成
n_rows = 1000
dates = pd.date_range(start='2023-01-01', end='2023-12-31', freq='D')
stores = ['Store_' + str(i) for i in range(1, 6)]
categories = ['Electronics', 'Clothing', 'Groceries', 'Home Goods']

data = {
    'Date': np.random.choice(dates, n_rows),
    'Store': np.random.choice(stores, n_rows),
    'Category': np.random.choice(categories, n_rows),
    'Sales': np.random.randint(100, 1000, n_rows),
    'Units': np.random.randint(1, 50, n_rows)
}

df = pd.DataFrame(data)

# データを日付でソート
df = df.sort_values('Date').reset_index(drop=True)

print(df.head())
print("\nデータフレームの情報:")
print(df.info())

        Date    Store     Category  Sales  Units
0 2023-01-01  Store_4     Clothing    628      5
1 2023-01-01  Store_2     Clothing    162      5
2 2023-01-01  Store_5     Clothing    148     48
3 2023-01-01  Store_4  Electronics    186     20
4 2023-01-01  Store_1     Clothing    607     40

データフレームの情報:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      1000 non-null   datetime64[ns]
 1   Store     1000 non-null   object
 2   Category  1000 non-null   object
 3   Sales     1000 non-null   int64
 4   Units     1000 non-null   int64
dtypes: datetime64[ns](1), int64(2), object(2)
memory usage: 39.2+ KB
None

# 前提：上記で生成したデータフレーム 'df' を使用します。

# 問題1: 各店舗の総売上金額を計算し、降順で表示してください。

# 問題2: カテゴリーごとの平均販売個数を計算し、昇順で表示してください。

# 問題3: 月ごとの総売上金額を計算し、折れ線グラフで表示してください。

# 問題4: 店舗とカテゴリーごとの総売上金額を計算し、ピボットテーブルで表示してください。

# 問題5: 各日付の、最も売上金額が高かった店舗とその売上金額を表示してください。

# 問題6: 週ごとの総売上金額を計算し、前週比の増減率も併せて表示してください。