data-analysis-basic-kadaiリポジトリへpractice_extra1フォルダまたはpractice_extra1.ipynbを作成し以下格納する

In [1]:
import pandas as pd
import numpy as np

# 問題1
print("問題1")
df1 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df2 = pd.DataFrame({'A': [5, 6], 'B': [7, 8]})
print("df1:")
display(df1)
print("\ndf2:")
display(df2)
print("\n以上の2つのDataFrameを縦方向に結合してください。")

問題1
df1:
   A  B
0  1  3
1  2  4

df2:
   A  B
0  5  7
1  6  8

以上の2つのDataFrameを縦方向に結合してください。

In [2]:

# 問題2
print("問題2")
df3 = pd.DataFrame({'id': [1, 2, 3], 'name': ['Alice', 'Bob', 'Charlie']})
df4 = pd.DataFrame({'id': [1, 2, 4], 'age': [25, 30, 35]})
print("df3:")
display(df3)
print("\ndf4:")
display(df4)
print("\n以上の2つのDataFrameを'id'列をキーにしてマージしてください。")

# 解答2

問題2
df3:
   id     name
0   1    Alice
1   2      Bob
2   3  Charlie

df4:
   id  age
0   1   25
1   2   30
2   4   35

以上の2つのDataFrameを'id'列をキーにしてマージしてください。

In [3]:
# 問題3
print("問題3")
df5 = pd.DataFrame({
    'category': ['A', 'B', 'A', 'B', 'A', 'C'],
    'value': [10, 20, 30, 40, 50, 60]
})
print("df5:")
display(df5)
print("\n'category'ごとの'value'の平均を計算してください。")

問題3
df5:
  category  value
0        A     10
1        B     20
2        A     30
3        B     40
4        A     50
5        C     60

'category'ごとの'value'の平均を計算してください。

In [4]:
# 問題4
print("問題4")
df6 = pd.DataFrame({
    'date': ['2023-01-01', '2023-01-01', '2023-01-02', '2023-01-02'],
    'product': ['A', 'B', 'A', 'B'],
    'sales': [100, 150, 200, 250]
})
print("df6:")
display(df6)
print("\n'date'を行、'product'を列、'sales'を値とするピボットテーブルを作成してください。")

問題4
df6:
         date product  sales
0  2023-01-01       A    100
1  2023-01-01       B    150
2  2023-01-02       A    200
3  2023-01-02       B    250

'date'を行、'product'を列、'sales'を値とするピボットテーブルを作成してください。